Online_Shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Online_Shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('',HomeView.as_view(),name='home' ),
    path('<slug:slug>/',ProductDetailView.as_view(),name='product_detail'),
    path('category/<slug:slug>/',HomeView.as_view(),name='category_filter'),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('cart/',CartView.as_view(),name='cart'),
    path('cart/add/<int:pk>/',CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:pk>/',CartRemoveView.as_view(),name='cart_remove'),
    path('apply/<int:pk>/',CouponApplyView.as_view(),name='apply_coupon'),
]

home/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE,related_name='scategory',null=True,blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural ='Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category_filter',args=[self.slug,])

class Product(models.Model):
    category = models.ManyToManyField(Category,related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    description = RichTextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('home:product_detail',args=[self.slug,])

home/views.py
from django.shortcuts import render , get_object_or_404
from django.views import View

from orders.forms import CartAddForm
from .models import Product  ,Category

# Create your views here.


class HomeView(View):
    def get(self,request,*args,**kwargs):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if 'slug' in kwargs:
            category = Category.objects.get(slug=kwargs['slug'])
            products = products.filter(category=category)
        return render(request, 'home/home.html',context={'products':products,'categories':categories})


class ProductDetailView(View):
    form_class_cart = CartAddForm
    def get(self,request,*args,**kwargs):
        product = get_object_or_404(Product,slug = kwargs['slug'])
        form = self.form_class_cart
        return render(request,'home/detail.html',context={'product':product,'form':form})

home/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}
     <h3 class="text-center">Products Detail</h3>
        <div class="d-flex justify-content-center">
            <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{{ product.image.url }}">
              <div class="card-body">
              <small class="card-subtitle mb-2 mt-2 text-muted">{{ product.created }}</small>
                <br>
                <h3 class="card-title">{{ product.name }}</h3>
                <p>{{ product.price }} Toman</p>
                  <p>{{ product.description|safe }}</p>
                  <br>
                  <form method="post" action="{% url 'order:cart_add' product.id %}">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <input type="submit" value="add to cart">
                  </form>
              </div>
            </div>
        </div>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}
{% block content %}
     <h3 class="text-center">Products</h3>
    <br> <br>
        {% for product in products %}
              <div class="card mt-3 m-2" style="width: 18rem;display: inline-block">
                  <img style="height: 286px;width: 286px;" class="card-img-top" src="{{ product.image.url }}">
                  <div class="card-body">
                    <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
                  </div>
                </div>
    {% endfor %}


{% endblock %}