Online_Shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Online_Shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
    path('verify/',views.UserRegisterVerifyCodeView.as_view(),name='verify_code'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('',HomeView.as_view(),name='home' ),
    path('<slug:slug>/',ProductDetailView.as_view(),name='product_detail'),
    path('category/<slug:slug>/',HomeView.as_view(),name='category_filter'),
]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('cart/',CartView.as_view(),name='cart'),
    path('cart/add/<int:pk>/',CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:pk>/',CartRemoveView.as_view(),name='cart_remove'),
    path('apply/<int:pk>/',CouponApplyView.as_view(),name='apply_coupon'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">
            {{ msg }}
        </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<div class="sticky-top bg-dark p-2 shadow " style="--bs-bg-opacity:0.95">
      <nav class="navbar navbar-expand-lg container" >
        <div class="container-fluid">
          <a class="navbar-brand fs-4 text-white" href="#">Shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url 'home:home' %}">Home</a>
              </li>
                <li class="nav-item">
                <a class="nav-link text-white" href="#navbarFeatures">About</a>
              </li>
                <li class="nav-item">
                <a class="nav-link text-white" href="#navbarFeatures">Contact</a>
              </li>
                <div id="navbarNavDarkDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li><a class="dropdown-item" aria-current="page" href="{% url 'order:cart' %}">
                            {% for item in categories %}
                                {% if item.scategory.all %}
                                            <li><a class="dropdown-item" href="{{ item.get_absolute_url  }}">{{ item }}</a></li>

                                    {% else %}
                                    <li><a class="dropdown-item" href="{{ item.get_absolute_url  }}">{{ item }}</a></li>
                                {% endif %}
                                {% for i in item.scategory.all %}
                                    <br>
                                        <a href="{{ i.get_absolute_url }}" class="dropdown-item">{{ i }}</a>
                                    {% endfor %}
                                <hr>
                            {% endfor %}
                        </a></li>

                      </ul>
                    </li>
                  </ul>
                </div>
            </ul>
            {% if request.user.is_authenticated %}
                <div id="navbarNavDarkDropdown">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Profile
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li><a class="dropdown-item" aria-current="page" href="{% url 'order:cart' %}">Cart {{ cart|length }}</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a></li>

                      </ul>
                    </li>
                  </ul>
                </div>
        {% else %}
                 <a class="nav-link text-white" aria-current="page" href="{% url 'accounts:user_register' %}">Register / </a>
                  <a class="nav-link text-white" aria-current="page" href="{% url 'accounts:user_login' %}"> Login</a>
          {% endif %}
          </div>
        </div>
      </nav>
    </div>